### ISSUE TITLE
Path to 'nuget.exe' is broken

### ISSUE THREAD

**Issue by brianstringfellow** [Azure-Samples/service-fabric-aad-helpers#1]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
```
$Configobj = .\SetupApplications.ps1 -TenantId '0e3d2646-78b3-4711-b8be-74a381d9890c' -ClusterName 'mysftestcluster' -WebApplicationReplyUrl 'https://mysftestcluster.eastus.cloudapp.azure.com:19080/Explorer/index.html' -AddResourceAccess
.\SetupUser.ps1 -ConfigObj $Configobj -UserName 'TestUser' -Password 'P@ssword!123'
.\SetupUser.ps1 -ConfigObj $Configobj -UserName 'TestAdmin' -Password 'P@ssword!123' -IsAdmin
```

### Any log messages given by the failure
![image](https://user-images.githubusercontent.com/22823524/63728199-ac2dda80-c817-11e9-9a61-747b963c6208.png)

### Expected/desired behavior
Successful execution of script and able to execute on 'nuget.exe' in same directory.

### OS and Version?
Windows 10. 

### Versions
>

### Mention any other details that might be useful
Modified 'Common.ps1' with '& .\nuget.exe install $ADPackage > nuget.log
' and the script executed fine.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jagilber** [comment]
potential fix in #8
